Add player samples and favicon in server list ping response
mcpyproject/mcpy pull request #24
Opened 2020-08-15 21:04 UTC by Geolykt

This PR may be dependent on #20 , however I did not check.

The favIcon is currently hardcoded to be favicon.png, but that will be changeable as soon as we have a proper way for adding configurations :)
Only tested to work with #20 as I'm using Windows 10 1903

2020-08-15 21:06 UTC, ntoskrnl4 commented
The default server icon for vanilla/Spigot/Paper is `server-icon.png`, it should be that by default

2020-08-15 21:08 UTC, Geolykt commented
Okay, changed

2020-08-23 02:30 UTC, tazz4843 approved these changes

2020-08-23 02:32 UTC, tazz4843 requested changes
Please update this PR to use the new code style created in #20 as it changed up the location of a lot of functions, etc.

2020-08-23 19:12 UTC, Geolykt commented
This code is severely outdated and I got no time on updating it

2020-08-23 19:12 UTC, closed without merging

2020-08-23 19:14 UTC, Geolykt commented on main.py
> +    taskData = {'function': func, 'args': args, 'kwargs': kwargs}
I really hate git