Update issue templates
mcpyproject/mcpy pull request #30
Opened 2020-08-23 02:48 UTC by tazz4843

2020-08-23 06:43 UTC, Geolykt approved these changes
Nothing wrong

2020-08-30 14:38 UTC, 0ddlyoko requested changes
Some sentences that, for me, should be better ;)

2020-08-30 14:38 UTC, 0ddlyoko commented on .github/ISSUE_TEMPLATE/feature_request.md
> +A clear and concise description of what you want to happen.
I think it's still an XY Problem
A sentence that looks like "Describe the goal of the feature" or "Describe what the feature should do" is more appropriated

2020-08-30 14:38 UTC, 0ddlyoko commented on .github/ISSUE_TEMPLATE/feature_request.md
> +A clear and concise description of any alternative features you've considered.
Same here (maybe "Describe alternatives of this feature" or something better) ?

2020-08-30 16:18 UTC, 0ddlyoko approved these changes

2020-08-30 16:20 UTC, merged