Develop
mcpyproject/mcpy pull request #54
Opened 2020-12-27 01:52 UTC by DevBennyturtle

Fixed startup.py and allowed parameters to be forwarded to Server.py
having issues with something calling startup.py after launch
I think it has always been happening but there were no print statements in main.py so we never noticed it

2020-12-27 01:54 UTC, hydrostaticcog commented
This needs to target the develop branch

2020-12-27 10:01 UTC, Geolykt commented
This PR is conflicting with #53 , I would wait until that one is released to build you changes ontop of that one or PR into that PR.

2020-12-27 10:06 UTC, Geolykt requested changes
Bloated diff, cannot review properly

2020-12-27 10:06 UTC, Geolykt commented on classes/Server.py
> +import logging
You did something to this file that I don't like.
 I recommend you to look at the line endings and text encoding again.

We only support UTF-8 as of now and I got no idea what the line endings are.
Of course we are up to debate to change something like this

2020-12-27 10:06 UTC, Geolykt commented on classes/mcPy/McPy.py
> +import logging
Same here

2020-12-27 10:06 UTC, Geolykt commented on startup.py
> +# coding=utf-8
Same here

2021-01-20 13:36 UTC, ntoskrnl4 requested changes
Check your line endings in your IDE. As is, all of the line endings are different, which makes this impossible to review or accept.

2021-01-26 02:22 UTC, hydrostaticcog commented
Author left project

2021-01-26 02:22 UTC, closed without merging

2021-01-26 02:28 UTC, ntoskrnl4 commented
more specifically, they never actually fixed the problems with the PR

2021-01-26 02:33 UTC, hydrostaticcog commented
Correct, its a combination of both. Author left project, therefore cannot fix issues.